### ISSUE TITLE
"No data found" error

### ISSUE THREAD

**Issue by usdivad** [caillonantoine/RAVE#17]
Hi there! First off, thanks so much for this awesome work -- the examples I've seen+heard are fantastic and I'm really excited to try it out for myself.

I'm coming across this error when training:
```
➜  RAVE git:(master) ✗ python3 train_rave.py --name death1 --wav /Users/usdivad/Documents/projects/misc/death.wav  --preprocessed ./death1/rave 
Recursive search in /Users/usdivad/Documents/projects/misc/death.wav
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/Users/usdivad/Documents/projects/misc/RAVE/train_rave.py", line 76, in <module>
    dataset = SimpleDataset(
  File "/usr/local/lib/python3.9/site-packages/udls/simple_dataset.py", line 83, in __init__
    raise Exception("No data found !")
Exception: No data found !
```

I do see a death1/rave/data.mdb file generated, but it's only about 8KB (the original wav file is 36MB). Do you know if there's a step or option that I might be missing? I feel like there's probably something basic that I'm not doing properly. (I tried with the docs/darbouka_prior.mp3 that comes in the repo as well, and get the same error)

Also, where are the pretrained models located? I see reference to "./rave_pretrained/darbouka/rave.ckpt" in #12, but don't actually see that directory or file in the repo itself.

Thanks!

**Comment by usdivad** [comment]
Aha... immediately after posting this I decided to try passing in the path to the parent directory (/Users/usdivad/Documents/projects/misc/) instead of the path to the wav file itself, and that seems to have done the trick. Now I'm getting the issue described in #10, but that's another matter.

Closing this now -- sorry for the false alarm!
