### ISSUE TITLE
Error in training

### ISSUE THREAD

**Issue by iamzoltan** [caillonantoine/RAVE#28]
Hello,

thanks so much for this work! I am exciting to get it working and dig into the paper.

I am trying to train rave on a folder of .wav files, but I can't seem to figure out how to get things going. I print the size of the train and val sets, and I get 1 and 0 respectively. It seems like all the data is not loading. If just use the train as also the validation, then I end up with this error:

```Validation sanity check:   0%|                                                                                    | 0/1 [00:00<?, ?it/s]/home/user/code/RAVE/py39env/lib/python3.9/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Traceback (most recent call last):
  File "/home/user/code/RAVE/train_rave.py", line 154, in <module>
    trainer.fit(model, train, val)
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _dispatch
    self.accelerator.start_training(self)
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in run_stage
    return self._run_train()
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1035, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1122, in _run_sanity_check
    self._evaluation_loop.run()
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 94, in advance
    batch_idx, batch = next(dataloader_iter)
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/code/RAVE/py39env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
TypeError: 'DataLoader' object is not subscriptable

```

not sure what to do, at a little bit of a loss.

thanks for your time :)

**Comment by caillonantoine** [comment]
It seems that there has been a mixup between a dataset and a dataloader class! I suggest you revert the train script to its original state and use a larger dataset !

**Comment by iamzoltan** [comment]
Thanks, I solved this now! but I now get the same problem as the latest comment on issue #27

**Comment by pgm-n117** [comment]
@iamzoltan do you solved it **by using a larger dataset** and then get the same issue as me on #27 ??

**Comment by caillonantoine** [comment]
I'm closing this issue.  We'll continue the discussion in #27
